version: "3"
services:
  provider:
    container_name: provider
    image: provider:latest
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - ".:/usr/src/app"
      - shared:/opt/data

volumes:
  shared:
    external: true
